# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 680)
        MainWindow.setMinimumSize(QtCore.QSize(530, 680))
        MainWindow.setMaximumSize(QtCore.QSize(530, 680))
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(136, 4, 37, 255), stop:0.129808 rgba(72, 2, 20, 255), stop:0.413462 rgba(0, 0, 0, 255));\n"
"}\n"
"\n"
"QLineEdit#display_output {\n"
"    background-color: transparent;\n"
"    color: #55ead4;\n"
"    border: 2px solid #c5003c;\n"
"    border-radius: 2px;\n"
"    padding: 15px;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 26pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit#display_output:hover {\n"
"    border: 2px solid #55ead4;\n"
"}\n"
"\n"
"QLineEdit#display_output:focus {\n"
"    border: 2px solid #55ead4;\n"
"    background-color: rgba(85, 234, 212, 0.05);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #c5003c;\n"
"    border-radius: 2px;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 16pt;\n"
"    font-weight: bold;\n"
"    color: #c5003c;\n"
"    padding: 12px;\n"
"    min-width: 60px;\n"
"    min-height: 60px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #55ead4;\n"
"    color: #55ead4;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #55ead4 !important;\n"
"    border: 2px solid #55ead4;\n"
"    color: #000000 !important;\n"
"    padding: 13px 11px 11px 13px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(530, 680))
        self.centralwidget.setMaximumSize(QtCore.QSize(530, 680))
        self.centralwidget.setObjectName("centralwidget")
        self.display_output = QtWidgets.QLineEdit(self.centralwidget)
        self.display_output.setGeometry(QtCore.QRect(10, 10, 510, 120))
        self.display_output.setMinimumSize(QtCore.QSize(510, 120))
        self.display_output.setMaximumSize(QtCore.QSize(510, 120))
        self.display_output.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.display_output.setReadOnly(True)
        self.display_output.setObjectName("display_output")
        self.ctrl_percent = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_percent.setGeometry(QtCore.QRect(10, 140, 120, 88))
        self.ctrl_percent.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_percent.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_percent.setObjectName("ctrl_percent")
        self.ctrl_ce = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_ce.setGeometry(QtCore.QRect(140, 140, 120, 88))
        self.ctrl_ce.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_ce.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_ce.setObjectName("ctrl_ce")
        self.ctrl_c = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_c.setGeometry(QtCore.QRect(270, 140, 120, 88))
        self.ctrl_c.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_c.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_c.setObjectName("ctrl_c")
        self.ctrl_delete = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_delete.setGeometry(QtCore.QRect(400, 140, 120, 88))
        self.ctrl_delete.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_delete.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_delete.setObjectName("ctrl_delete")
        self.ctrl_inverse = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_inverse.setGeometry(QtCore.QRect(10, 230, 120, 88))
        self.ctrl_inverse.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_inverse.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_inverse.setObjectName("ctrl_inverse")
        self.ctrl_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_sqrt.setGeometry(QtCore.QRect(270, 230, 120, 88))
        self.ctrl_sqrt.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_sqrt.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_sqrt.setObjectName("ctrl_sqrt")
        self.ctrl_square = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_square.setGeometry(QtCore.QRect(140, 230, 120, 88))
        self.ctrl_square.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_square.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_square.setObjectName("ctrl_square")
        self.op_div = QtWidgets.QPushButton(self.centralwidget)
        self.op_div.setGeometry(QtCore.QRect(400, 230, 120, 88))
        self.op_div.setMinimumSize(QtCore.QSize(88, 88))
        self.op_div.setMaximumSize(QtCore.QSize(120, 80))
        self.op_div.setObjectName("op_div")
        self.num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7.setGeometry(QtCore.QRect(10, 320, 120, 88))
        self.num_7.setMinimumSize(QtCore.QSize(88, 88))
        self.num_7.setMaximumSize(QtCore.QSize(120, 80))
        self.num_7.setObjectName("num_7")
        self.num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.num_8.setGeometry(QtCore.QRect(140, 320, 120, 88))
        self.num_8.setMinimumSize(QtCore.QSize(88, 88))
        self.num_8.setMaximumSize(QtCore.QSize(120, 80))
        self.num_8.setObjectName("num_8")
        self.op_mul = QtWidgets.QPushButton(self.centralwidget)
        self.op_mul.setGeometry(QtCore.QRect(400, 320, 120, 88))
        self.op_mul.setMinimumSize(QtCore.QSize(88, 88))
        self.op_mul.setMaximumSize(QtCore.QSize(120, 80))
        self.op_mul.setObjectName("op_mul")
        self.num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.num_9.setGeometry(QtCore.QRect(270, 320, 120, 88))
        self.num_9.setMinimumSize(QtCore.QSize(88, 88))
        self.num_9.setMaximumSize(QtCore.QSize(120, 80))
        self.num_9.setObjectName("num_9")
        self.num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.num_6.setGeometry(QtCore.QRect(270, 410, 120, 88))
        self.num_6.setMinimumSize(QtCore.QSize(88, 88))
        self.num_6.setMaximumSize(QtCore.QSize(120, 80))
        self.num_6.setObjectName("num_6")
        self.num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.num_4.setGeometry(QtCore.QRect(10, 410, 120, 88))
        self.num_4.setMinimumSize(QtCore.QSize(88, 88))
        self.num_4.setMaximumSize(QtCore.QSize(120, 80))
        self.num_4.setObjectName("num_4")
        self.op_sub = QtWidgets.QPushButton(self.centralwidget)
        self.op_sub.setGeometry(QtCore.QRect(400, 410, 120, 88))
        self.op_sub.setMinimumSize(QtCore.QSize(88, 88))
        self.op_sub.setMaximumSize(QtCore.QSize(120, 80))
        self.op_sub.setObjectName("op_sub")
        self.num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.num_5.setGeometry(QtCore.QRect(140, 410, 120, 88))
        self.num_5.setMinimumSize(QtCore.QSize(88, 88))
        self.num_5.setMaximumSize(QtCore.QSize(120, 80))
        self.num_5.setObjectName("num_5")
        self.num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.num_3.setGeometry(QtCore.QRect(270, 500, 120, 88))
        self.num_3.setMinimumSize(QtCore.QSize(88, 88))
        self.num_3.setMaximumSize(QtCore.QSize(120, 80))
        self.num_3.setObjectName("num_3")
        self.num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_1.setGeometry(QtCore.QRect(10, 500, 120, 88))
        self.num_1.setMinimumSize(QtCore.QSize(88, 88))
        self.num_1.setMaximumSize(QtCore.QSize(120, 80))
        self.num_1.setObjectName("num_1")
        self.op_add = QtWidgets.QPushButton(self.centralwidget)
        self.op_add.setGeometry(QtCore.QRect(400, 500, 120, 88))
        self.op_add.setMinimumSize(QtCore.QSize(88, 88))
        self.op_add.setMaximumSize(QtCore.QSize(120, 80))
        self.op_add.setObjectName("op_add")
        self.num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.num_2.setGeometry(QtCore.QRect(140, 500, 120, 88))
        self.num_2.setMinimumSize(QtCore.QSize(88, 88))
        self.num_2.setMaximumSize(QtCore.QSize(120, 80))
        self.num_2.setObjectName("num_2")
        self.num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.num_0.setGeometry(QtCore.QRect(140, 590, 120, 88))
        self.num_0.setMinimumSize(QtCore.QSize(88, 88))
        self.num_0.setMaximumSize(QtCore.QSize(120, 80))
        self.num_0.setObjectName("num_0")
        self.num_dot = QtWidgets.QPushButton(self.centralwidget)
        self.num_dot.setGeometry(QtCore.QRect(270, 590, 120, 88))
        self.num_dot.setMinimumSize(QtCore.QSize(88, 88))
        self.num_dot.setMaximumSize(QtCore.QSize(120, 80))
        self.num_dot.setObjectName("num_dot")
        self.btn_equals = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equals.setGeometry(QtCore.QRect(400, 590, 120, 88))
        self.btn_equals.setMinimumSize(QtCore.QSize(88, 88))
        self.btn_equals.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_equals.setObjectName("btn_equals")
        self.ctrl_sign = QtWidgets.QPushButton(self.centralwidget)
        self.ctrl_sign.setGeometry(QtCore.QRect(10, 590, 120, 88))
        self.ctrl_sign.setMinimumSize(QtCore.QSize(88, 88))
        self.ctrl_sign.setMaximumSize(QtCore.QSize(120, 80))
        self.ctrl_sign.setObjectName("ctrl_sign")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display_output.setText(_translate("MainWindow", "0"))
        self.ctrl_percent.setText(_translate("MainWindow", "%"))
        self.ctrl_ce.setText(_translate("MainWindow", "CE"))
        self.ctrl_c.setText(_translate("MainWindow", "C"))
        self.ctrl_delete.setText(_translate("MainWindow", "Delete"))
        self.ctrl_inverse.setText(_translate("MainWindow", "1/x"))
        self.ctrl_sqrt.setText(_translate("MainWindow", "√x"))
        self.ctrl_square.setText(_translate("MainWindow", "x²"))
        self.op_div.setText(_translate("MainWindow", "/"))
        self.num_7.setText(_translate("MainWindow", "7"))
        self.num_8.setText(_translate("MainWindow", "8"))
        self.op_mul.setText(_translate("MainWindow", "*"))
        self.num_9.setText(_translate("MainWindow", "9"))
        self.num_6.setText(_translate("MainWindow", "6"))
        self.num_4.setText(_translate("MainWindow", "4"))
        self.op_sub.setText(_translate("MainWindow", "-"))
        self.num_5.setText(_translate("MainWindow", "5"))
        self.num_3.setText(_translate("MainWindow", "3"))
        self.num_1.setText(_translate("MainWindow", "1"))
        self.op_add.setText(_translate("MainWindow", "+"))
        self.num_2.setText(_translate("MainWindow", "2"))
        self.num_0.setText(_translate("MainWindow", "0"))
        self.num_dot.setText(_translate("MainWindow", "."))
        self.btn_equals.setText(_translate("MainWindow", "="))
        self.ctrl_sign.setText(_translate("MainWindow", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())